module.exports = {
    success:{
        LOGIN:'Login successful',
        REGISTER:'Register successful',
        PROFILE_UPDATED:'Profile updated successful',
        FORGOT_PASSWORD_SENT:'Forgot password sent successful',
        LOGOUT:'Logout successful',
        META_TAG_INSERT:'Meta Tag added successfull',
        META_TAG_DELETED:'Meta Tag deleted successfull',
        TAG_INSERT:'Tag added successfull',
        TAG_UPDATE:'Tag updated successfull',
        TAG_DELETED:'Tag deleted successfull',
        INGREDIENTS_INSERT:'Ingredients added successfull',
        INGREDIENTS_DELETED:'Ingredients deleted successfull',
        INGREDIENTS_UPDATED:'Ingredients updated successfull',
        MENU_INSERT:'Menu added successfull',
        MENU_UPDATE:'Menu updated successfull',
        MENU_DELETED:'Menu deleted successfull',
        CATEGORY_INSERT:'Category added successfull',
        CATEGORY_UPDATED:'Category updated successfull',
        POST_COMMENT_UPDATED:'Comment updated successfull',
        CATEGORY_DELETED:'Category deleted successfull',
        POST_COMMENT_DELETED:'Comment deleted successfull',
        OTP_SENT: 'Otp sent successfully',
        OTP_VERIFIED: 'Otp verified successfully',
        IMAGE_DELETED: 'Image delete successfully',
        VIDEO_DELETED: 'Video deleted successfully'     
    },
    error:{
        INVALID_LOGIN:'Invalid login credentials',
        UNABLE_REGISTER:'Unable to register',
        USER_ALLREADY_EXIST:'User already exist',
        PASSWORD_NOT_MATCHED:'Password did not matched',
        USER_NOT_EXIST:'User not exist',
        SOMETHING_WRONG:'Something went wrong',
        BRAND_NOT_FOUND:'Brand not found',
        TAG_NOT_FOUND:'Tag not found',
        META_TAG_NOT_FOUND:'Meta Tag not found',
        INGREDIENTS_NOT_FOUND:'Ingredients not found',
        MENU_NOT_FOUND:'Menu not found',
        CATEGORY_NOT_FOUND:'Category not found',
        POST_COMMENT_NOT_FOUND:'comment not found',
        POST_NOT_FOUND:'No post found',
        INVALID_OTP: 'Invalid OTP',
        IMAGE_NOT_FOUND: 'Imgae not found',
        VIDEO_NOT_FOUND: 'Video not found'
    },

};